---
sudo: false
language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.1.6
  - 2.2.2
env:
  - PUPPET_GEM_VERSION="~> 3.0"
  - PUPPET_GEM_VERSION="~> 4.0"
matrix:
  exclude:
    - rvm: 2.2.2
      env: PUPPET_GEM_VERSION="~> 3.0"
script: bundle exec rake spec
