language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: "rake spec"
env:
  - PUPPET_VERSION=2.7.23
  - PUPPET_VERSION=3.4.3
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.7.23
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7.23
    - rvm: 2.1.0
      env: PUPPET_VERSION=2.7.23
